version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/venda
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=kronos6
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080" # Expor a porta 8080 do contêiner para a porta 8080 do host

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=venda
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kronos6
    ports:
      - "5432:5432" # Expor a porta 5432 do contêiner para a porta 5432 do host
